services:
  app:
    build: .                       # constru√Øm imatge des del Dockerfile
    container_name: appiso2-app
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - "1234:3000"               # host:contenidor
    volumes:
      - db-data:/app               # persistir tota la carpeta /app
    restart: unless-stopped

volumes:
  db-data:
